name: "frontend build publish"

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: "actions/checkout@v2"

      - name: Build docker image
        run: |
          docker image build -t frontend ./frontend